{{ range $key,$val := .Values.applications }}
{{ if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  project: default
  source:
    chart: {{ $key }}
    repoURL: {{ $val.chartRepoURL }}
    targetRevision: {{ $val.chartVersion }}
    values: | 
      {{ $skeletonValues := tpl ($.Files.Get (printf "values/%s/skeleton.yaml" $key)) $ | fromYaml }}
      {{ $clusterValues := $.Files.Get (printf "values/%s/%s.yaml" $key $.Values.clusterName ) | fromYaml }}
      {{- mustMergeOverwrite $skeletonValues $clusterValues | toYaml | nindent 6 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ $val.namespace }}
{{- end }}
{{- end }}