{{ range $key,$val := .Values.applications }}
{{ if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  project: default
  source:
    chart: {{ $key }}
    repoURL: {{ $val.chartRepoURL }}
    targetRevision: {{ $val.chartVersion }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ $val.namespace }}
{{- end }}
{{- end }}