apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master
  namespace: argocd
spec:
  project: default
  source:
      path: master
      repoURL: https://github.com/JacobAmar/argo-test.git
      targetRevision: HEAD
      helm:
        valueFiles:
        - clusters/dev-01.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd