{{ range $key,$val := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $val.namespace }}
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus
      targetRevision: 15.7.1
      helm:
        valueFiles:
          - $values/values/{{ $key }}/values.yaml
          - $values/values/{{ $key }}/{{ $.Values.clusterName }}.yaml
    - repoURL: https://github.com/JacobAmar/argo-test.git
      targetRevision: {{ $val.valuesRevision }}
      ref: values
{{- end }}