region: 
applications:
  kube-prometheus:
     enabled: true
     namespace: monitoring
     type: helm
     chartRepoURL: https://charts.bitnami.com/bitnami
     chartVersion: 1.14.5
     syncWave: -1
  test-app:
      enabled: true
      path: test
      namespace: test
      chartRepoURL: https://github.com/JacobAmar/argo-test.git
      chartVersion: HEAD
