region: 
applications:
  kube-prometheus:
     enabled: true
     namespace: monitoring
     type: helm
     chartRepoURL: https://charts.bitnami.com/bitnami
     chartVersion: 9.1.1
     syncWave: -1
     syncOptions:
       - ServerSideApply=true

  test-app:
      enabled: true
      path: test
      namespace: test
      chartRepoURL: https://github.com/JacobAmar/argo-test.git
      chartVersion: HEAD
