region: 
applications:
  cert-manager:
     enabled: true
     namespace: cert-manager
     type: helm
     chartRepoURL: https://charts.jetstack.io
     chartVersion: 1.14.5
     syncWave: -1
  test-app:
      enabled: true
      path: test
      namespace: test
      chartRepoURL: https://github.com/JacobAmar/argo-test.git
      chartVersion: HEAD
