region: 
applications:
  cluster-autoscaler:
     enabled: true
     namespace: cert-manager
     type: helm
     chartRepoURL: https://charts.jetstack.io
     chartVersion: 9.36.0
     syncWave: -1
  test-app:
      enabled: true
      path: test
      namespace: test
      chartRepoURL: https://github.com/JacobAmar/argo-test.git
      chartVersion: HEAD
